name: hawiah_client
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: "none"

# Version and build number
version: 1.0.18+22

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.7
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  get_it: ^9.0.5
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.16
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.1
  intl_phone_number_input: ^0.7.4
  toggle_switch: ^2.3.0
  pinput: ^6.0.1
  easy_stepper: ^0.9.1
  awesome_dialog: ^3.2.1
  awesome_bottom_bar: ^1.2.4
  searchable_listview: ^2.16.0
  bottom_picker: ^4.1.1
  table_calendar: ^3.1.2
  google_maps_flutter: ^2.12.0
  intl: ^0.20.2
  flutter_chat_ui: ^2.9.1
  file_picker: ^10.3.3
  image_picker: ^1.1.2
  open_filex: ^4.6.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  flutter_emoji_feedback: ^1.0.3
  curved_navigation_bar: ^1.0.6
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.3.1
  internet_connection_checker_plus: ^2.7.0
  hive_flutter: ^1.1.0
  fluttertoast: ^9.0.0
  hive: ^2.2.3
  bot_toast: ^4.1.3
  loading_indicator: ^3.1.1
  shimmer_animation: ^2.2.1
  flutter_widget_from_html: ^0.17.1
  flutter_html: ^3.0.0
  animations: ^2.0.11
  geocoding: ^4.0.0
  location: ^8.0.1
  country_picker: ^2.0.26
  gap: ^3.0.1
  internet_connection_checker: ^3.0.1
  timeago: ^3.7.0
  defer_pointer: ^0.0.2
  url_launcher:
  rename: ^3.1.0
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  googleapis_auth: ^2.0.0
  flutter_local_notifications: ^19.1.0
  grouped_list: ^6.0.0
  equatable: ^2.0.7
  photo_view: ^0.15.0
  new_version_plus: ^0.1.1
  webview_flutter: ^4.7.0
  rive: ^0.13.18


dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appWhiteLogoImage.png"
  min_sdk_android: 21

flutter:
  # Use Material Design icons
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/gifs/
    - assets/global_icon/
    - assets/svg/
  fonts:
    - family: DINNextLTArabic
      fonts:
        - asset: assets/font/DINNextLTArabic-Medium-4.ttf
          weight: 500
        - asset: assets/font/DINNextLTArabic-Bold-2.ttf
          weight: 700

flutter_native_splash:
  image: "assets/images/appWhiteLogoImage.png"
  color: "FFFFFF"
  android: true
  ios: true

flutter_lints: ^3.0.0
