name: hawiah_client
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: "none"

# Version and build number
version: 1.0.1+4

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.7
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^8.0.2
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.16
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.1
  intl_phone_number_input: ^0.7.4
  toggle_switch: ^2.3.0
  pinput: ^5.0.0
  easy_stepper: ^0.8.5+1
  awesome_dialog: ^3.2.1
  awesome_bottom_bar: ^1.2.4
  searchable_listview: ^2.16.0
  bottom_picker: ^2.9.0
  table_calendar: ^3.1.2
  google_maps_flutter: ^2.10.0
  intl: ^0.19.0
  flutter_chat_ui: ^1.6.15
  file_picker: ^8.1.7
  image_picker: ^1.1.2
  open_filex: ^4.6.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  flutter_emoji_feedback: ^0.4.0
  curved_navigation_bar: ^1.0.6
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.3.1
  internet_connection_checker_plus: ^2.7.0
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.12
  hive: ^2.2.3
  bot_toast: ^4.1.3
  loading_indicator: ^3.1.1
  shimmer_animation: ^2.2.1
  flutter_widget_from_html: ^0.16.0 
  animations: ^2.0.11
  geocoding: ^3.0.0
  location: ^7.0.0
  country_picker: ^2.0.26
  gap: ^3.0.1
  internet_connection_checker: ^1.0.0+1
  timeago: ^3.7.0
  defer_pointer: ^0.0.2
  url_launcher:
  rename: ^3.1.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  googleapis_auth: ^1.6.0
  flutter_local_notifications: ^19.1.0
  grouped_list: ^6.0.0
  equatable: ^2.0.7
  

  
dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/play_store.png"
  min_sdk_android: 21
  
  

flutter:
  # Use Material Design icons
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/gifs/
    - assets/global_icon/
    - assets/svg/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/Cairo-ExtraLight.ttf
          weight: 100
        - asset: assets/font/Cairo-Light.ttf
          weight: 300
        - asset: assets/font/Cairo-Regular.ttf
          weight: 400
        - asset: assets/font/Cairo-Medium.ttf
          weight: 500
        - asset: assets/font/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/font/Cairo-Bold.ttf
          weight: 700
        - asset: assets/font/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Cairo-Black.ttf
          weight: 900    

flutter_native_splash:
  image: 'assets/images/play_store.png'
  color: "FFFFFF"
  android: true
  ios: true

flutter_lints: ^3.0.0


